### ISSUE TITLE
You have a nixpkg now

### ISSUE THREAD

**Issue by TravisDavis-ops** [milgra/sov#15]
I created a nixpkg for this project its currently in nix unstable

**Comment by milgra** [comment]
yaaaay, it's visible in the repositories badge, thank you very much, we are slowly spreading! :)

**Comment by simoneruffini** [comment]
There is a problem with the default config file found in `/usr/share/sov/`. Since nix generates closed environments for each package, when you install sov the config file gets saved in `/nix/store/<some-hash>-sov-<version>/usr/share/sov/config` while `sov` expects them in `/usr/share/sov/config`. This means that if you launch the program it starts with no default configuration.

**Comment by simoneruffini** [comment]
So you are building the package instead of downloading the released binary, correct?

Moreover I'd suggest to add a parameter in the compilation since patches are precarious and need maintenence.

**Comment by TravisDavis-ops** [comment]
that's correct. could you make a new issue for that just to increase visibility, I'll look at making a pr for it, but for now this is ok.

**Comment by milgra** [comment]
Hopefully it got solved with [0.72](https://github.com/milgra/sov/releases/tag/0.72)
