### ISSUE TITLE
What type of color code does the css file use?

### ISSUE THREAD

**Issue by IceAsteroid** [milgra/sov#40]
Each color code has eight-digits, it looks really confusing, as regular color codes are either RGB or Hex, why in this case, do color codes have eight-digits?

The css file named main.css is located under /usr/local/share/sov/ along with the main.html file.

I couldn't find a converter online to convert a hex color code to octal color code that would convert it correctly. Once converting to octal, the color looked not the same.

Nor can I use just hex color codes, they just don't look right. :(

Any helps?

**Comment by trinitronx** [comment]
From my experimentation with changing `background-color` on the `#main` `div`, it appears that the color format is:

```
#BBGGRRAA
```

Where:

- `BB` = color blue value
- `GG` = color green value
- `RR` = color red value
- `AA` = color alpha channel value (transparency) 
  - `FF` = `255` = 100% Opaque = No transparency
  - `00` = `0` = 0% Opaque = Full transparency

That being said... it seems that this format differs from the usual standard expectations including Wayland & Sway, which both use the format: `#RRGGBBAA`.

It seems that the usual order of: `Red` + `Green` + `Blue` ...
has been flipped: `Blue` + `Green` + `Red`
I suspect that is a mistake, because CSS uses the standard: `#RRGGBB`.

**Comment by milgra** [comment]
Hi, I will look into this soon.
